name: qalbu
description: Capstone Project Team CPSG-26 MSIB Dicoding Batch 2

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.4
  google_fonts: ^3.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  flutter_html: ^3.0.0-alpha.3
  sqflite: ^2.0.2+1
  path: ^1.8.1
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/

  fonts:
    - family: At-Tupats
      fonts:
        - asset: assets/fonts/at-tupats.otf
    - family: Ramadhani
      fonts:
        - asset: assets/fonts/ramadhani.otf